<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="45.685" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2023-06-15T11:29:13" tests="0" file="cypress\e2e\UI\alerty.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="E2E - Alerty" timestamp="2023-06-15T11:29:13" tests="2" time="45.537" failures="2">
    <testcase name="E2E - Alerty Alert" time="7.321" classname="Alert">
      <failure message="Timed out retrying after 4000ms: The command was expected to run against origin `https://testowanie-oprogramowania.pl` but the application is at origin `https://a.tunnelbuilder.top`.

This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.

Using `cy.origin()` to wrap the commands run on `https://a.tunnelbuilder.top` will likely fix this issue.

`cy.origin(&apos;https://a.tunnelbuilder.top&apos;, () =&gt; {`
`  &lt;commands targeting https://a.tunnelbuilder.top go here&gt;`
`})`

https://on.cypress.io/cy-visit-succeeded-but-commands-fail" type="CypressError"><![CDATA[CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `https://testowanie-oprogramowania.pl` but the application is at origin `https://a.tunnelbuilder.top`.

This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.

Using `cy.origin()` to wrap the commands run on `https://a.tunnelbuilder.top` will likely fix this issue.

`cy.origin('https://a.tunnelbuilder.top', () => {`
`  <commands targeting https://a.tunnelbuilder.top go here>`
`})`

https://on.cypress.io/cy-visit-succeeded-but-commands-fail
    at cypressErr (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:164260:18)
    at Object.errByPath (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:164315:10)
    at Object.commandCanCommunicateWithAUT (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:161502:98)
    at <unknown> (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:148441:22)
    at Object.subjectFn (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:159297:16)
    at $Cy.verifyUpcomingAssertions (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:140519:31)
    at onRetry (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:159288:15)
    at tryCatcher (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:18744:23)
    at Promise.attempt.Promise.try (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:16018:29)
    at whenStable (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:156173:65)
    at <unknown> (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:155614:14)
    at tryCatcher (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:18744:23)
    at Promise._settlePromiseFromHandler (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:16679:31)
    at Promise._settlePromise (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:16736:18)
    at Promise._settlePromise0 (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:16781:10)
    at Promise._settlePromises (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:16861:18)
    at Promise._fulfill (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:16805:18)
    at <unknown> (https://testowanie-oprogramowania.pl/__cypress/runner/cypress_runner.js:18419:46)
From Your Spec Code:
    at get buttonAlert1 [as buttonAlert1] (webpack:///./cypress/support/Page-Object/alertPage.js:3:14)
    at alertPage.clickonButtonAlert1 (webpack:///./cypress/support/Page-Object/alertPage.js:11:13)
    at Context.eval (webpack:///./cypress/e2e/UI/alerty.js:8:18)]]></failure>
    </testcase>
    <testcase name="E2E - Alerty Confirm" time="4.168" classname="Confirm">
      <failure message="Timed out retrying after 4000ms: Expected to find element: `#alert-confirm`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find element: `#alert-confirm`, but never found it.
    at get buttonAlert2 [as buttonAlert2] (webpack:///./cypress/support/Page-Object/alertPage.js:7:14)
    at alertPage.clickonButtonAlert2 (webpack:///./cypress/support/Page-Object/alertPage.js:15:13)
    at Context.eval (webpack:///./cypress/e2e/UI/alerty.js:14:18)]]></failure>
    </testcase>
  </testsuite>
</testsuites>